import {
  ArrowLongDownIcon,
  ArrowLongUpIcon,
  ArrowLongRightIcon,
  ArrowsPointingInIcon,
  ArrowsPointingOutIcon,
  ArrowTopRightOnSquareIcon,
  Bars3Icon,
  BoltIcon,
  BookmarkIcon,
  CalendarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  ChevronUpIcon,
  ClockIcon,
  DocumentDuplicateIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  GifIcon,
  GiftIcon,
  GlobeAltIcon,
  HashtagIcon,
  HeartIcon,
  IdentificationIcon,
  InboxArrowDownIcon,
  InformationCircleIcon,
  LanguageIcon,
  LinkIcon,
  ListBulletIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  PaperClipIcon,
  PencilIcon,
  PlusIcon,
  QrCodeIcon,
  QuestionMarkCircleIcon,
  RocketLaunchIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShoppingCartIcon,
  SparklesIcon,
  Squares2X2Icon,
  StarIcon,
  TrashIcon,
  UserIcon,
  WalletIcon,
  XMarkIcon,
  BarsArrowDownIcon,
  ArrowLongLeftIcon,
  ArrowRightOnRectangleIcon,
  CheckCircleIcon,
  HomeIcon,
  UsersIcon,
  ArchiveBoxIcon,
} from "@heroicons/react/24/solid";
import {
  FunnelIcon,
  StarIcon as StarIconOpen
} from "@heroicons/react/24/outline";


export const iconList = {
  menu: Bars3Icon,
  chevronUp: ChevronUpIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  verticalDots: EllipsisVerticalIcon,
  dotsHorizontal: EllipsisHorizontalIcon,
  search: MagnifyingGlassIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  account: UserIcon,
  share: ShareIcon,
  star: StarIcon,
  starOpen: StarIconOpen,
  x: XMarkIcon,
  edit: PencilIcon,
  remove: TrashIcon,
  bookmark: BookmarkIcon,
  grid: Squares2X2Icon,
  list: ListBulletIcon,
  copy: DocumentDuplicateIcon,
  like: HeartIcon,
  trending: BoltIcon,
  link: LinkIcon,
  hashtag: HashtagIcon,
  help: QuestionMarkCircleIcon,
  info: InformationCircleIcon,
  exclamationTriangle: ExclamationTriangleIcon,
  identification: IdentificationIcon,
  check: CheckIcon,
  checkCircle: CheckCircleIcon,
  checkShield: ShieldCheckIcon,
  arrowUp: ArrowLongUpIcon,
  arrowDown: ArrowLongDownIcon,
  arrowRight: ArrowLongRightIcon,
  arrowLeft: ArrowLongLeftIcon,
  newTab: ArrowTopRightOnSquareIcon,
  fullScreen: ArrowsPointingOutIcon,
  normalScreen: ArrowsPointingInIcon,
  clock: ClockIcon,
  calendar: CalendarIcon,
  chevronUpDown: ChevronUpDownIcon,
  visible: EyeIcon,
  invisible: EyeSlashIcon,
  attachment: PaperClipIcon,
  download: InboxArrowDownIcon,
  globe: GlobeAltIcon,
  language: LanguageIcon,
  gif: GifIcon,
  gift: GiftIcon,
  qr: QrCodeIcon,
  rocket: RocketLaunchIcon,
  shoppingCart: ShoppingCartIcon,
  sparkles: SparklesIcon,
  wallet: WalletIcon,
  filter: FunnelIcon,
  barsArrowDown: BarsArrowDownIcon,
  logOut: ArrowRightOnRectangleIcon,
  home: HomeIcon,
  users: UsersIcon,
  archive: ArchiveBoxIcon,
  undefined: "undefined",
  number: "undefined",
};
