const backgroundOpacity = {
  full: "0", //transparant
  high: ".32",
  low: ".64",
  none: "1",
};

const backgroundPosition = {
  bottom: "bottom",
  center: "center",
  left: "left",
  "left-bottom": "left bottom",
  "left-top": "left top",
  right: "right",
  "right-bottom": "right bottom",
  "right-top": "right top",
  top: "top",
};

const borderWidth = {
  DEFAULT: "1px",
  0: "0px",
  1: "0.1rem",
  2: "2px",
  4: "4px",
  8: "8px",
  none: "none",
};

const borderRadius = {
  none: "0px",
  xs: "4px",
  small: "12px",
  medium: "16px",
  sm: "0.125rem",
  DEFAULT: "0.5rem",
  large: "1.5rem",
  md: "0.375rem",
  lg: "0.5rem",
  xl: "0.75rem",
  "2xl": "1rem",
  "3xl": "1.5rem",
  "extraLarge": "3rem",
  full: "9999px",
};


const columns = {
  auto: "auto",
  1: "1",
  2: "2",
  3: "3",
  4: "4",
  5: "5",
  6: "6",
  7: "7",
  8: "8",
  9: "9",
  10: "10",
  11: "11",
  12: "12",
  "3xs": "16rem",
  "2xs": "18rem",
  xs: "20rem",
  sm: "24rem",
  md: "28rem",
  lg: "32rem",
  xl: "36rem",
  "2xl": "42rem",
  "3xl": "48rem",
  "4xl": "56rem",
  "5xl": "64rem",
  "6xl": "72rem",
  "7xl": "80rem",
};

const fontWeight = {
  thin: "100",
  extralight: "200",
  light: "300",
  normal: "400",
  medium: "500",
  semibold: "600",
  bold: "700",
  extrabold: "800",
  black: "900",
};

const heights = {
  "1/2": "50%",
  "1/3": "33.333333%",
  "2/3": "66.666667%",
  "1/4": "25%",
  "2/4": "50%",
  "3/4": "75%",
  "1/5": "20%",
  "2/5": "40%",
  "3/5": "60%",
  "4/5": "80%",
  "1/6": "16.666667%",
  "2/6": "33.333333%",
  "3/6": "50%",
  "4/6": "66.666667%",
  "5/6": "83.333333%",
  full: "100%",
  screen: "100vh",
  min: "min-content",
  max: "max-content",
  fit: "fit-content",
};

const minWidth = {
  0: "0px",
  full: "100%",
  min: "min-content",
  max: "max-content",
  fit: "fit-content",
  spacer: "25px",
}

const widths = {
  auto: "auto",
  "1/2": "50%",
  "1/3": "33.333333%",
  "2/3": "66.666667%",
  "1/4": "25%",
  "2/4": "50%",
  "3/4": "75%",
  "1/5": "20%",
  "2/5": "40%",
  "3/5": "60%",
  "4/5": "80%",
  "1/6": "16.666667%",
  "2/6": "33.333333%",
  "3/6": "50%",
  "4/6": "66.666667%",
  "5/6": "83.333333%",
  "1/12": "8.333333%",
  "2/12": "16.666667%",
  "3/12": "25%",
  "4/12": "33.333333%",
  "5/12": "41.666667%",
  "6/12": "50%",
  "7/12": "58.333333%",
  "8/12": "66.666667%",
  "9/12": "75%",
  "10/12": "83.333333%",
  "11/12": "91.666667%",
  full: "100%",
  app: "90%",
  screen: "100vw",
  min: "min-content",
  max: "max-content",
  fit: "fit-content",
  half: "calc(50% - 0.5rem)",
  third: "calc(33% - 0.5rem)",
  quarter: "calc(25% - 0.5rem)",
  spacer: "60px",

};

const textOpacity = {
  full: "0", //transparant
  high: ".32",
  low: ".64",
  none: "1",
  40: ".4",
  50: ".5",
};

const gridTemplateColumns = {
  none: "none",
  1: "repeat(1, minmax(0, 1fr))",
  2: "repeat(2, minmax(0, 1fr))",
  3: "repeat(3, minmax(0, 1fr))",
  4: "repeat(4, minmax(0, 1fr))",
  5: "repeat(5, minmax(0, 1fr))",
  6: "repeat(6, minmax(0, 1fr))",
  7: "repeat(7, minmax(0, 1fr))",
  8: "repeat(8, minmax(0, 1fr))",
  9: "repeat(9, minmax(0, 1fr))",
  10: "repeat(10, minmax(0, 1fr))",
  11: "repeat(11, minmax(0, 1fr))",
  12: "repeat(12, minmax(0, 1fr))",
};

const fontSize = {
  8: ["0.5rem", { lineHeight: "1.5em", }],
  9: ["0.5625rem", { lineHeight: "1.5em", }],
  10: ["0.625rem", { lineHeight: "1.5em", }],
  12: ["0.75rem", { lineHeight: "1.5em", }],
  14: ["0.875rem", { lineHeight: "1.5em", }],
  base: ["0.875rem", { lineHeight: "0", }],
  16: ["1rem", { lineHeight: "1.5em", }],
  20: ["1.25rem", { lineHeight: "1.5em", }],
  24: ["1.5rem", { lineHeight: "1.5em", }],
  28: ["1.75rem", { lineHeight: "1.5em", }],
  32: ["2rem", { lineHeight: "1.5em", }],
  40: ["2.5rem", { lineHeight: "1.5em", }],
  48: ["3rem", { lineHeight: "1.5em", }],
  80: ["5rem", { lineHeight: "1.25em", }],
};

const cursor = {
  auto: "auto",
  default: "default",
  pointer: "pointer",
  wait: "wait",
  text: "text",
  move: "move",
  help: "help",
  "not-allowed": "not-allowed",
  none: "none",
  "context-menu": "context-menu",
  progress: "progress",
  cell: "cell",
  crosshair: "crosshair",
  "vertical-text": "vertical-text",
  alias: "alias",
  copy: "copy",
  "no-drop": "no-drop",
  grab: "grab",
  grabbing: "grabbing",
  "all-scroll": "all-scroll",
  "col-resize": "col-resize",
  "row-resize": "row-resize",
  "n-resize": "n-resize",
  "e-resize": "e-resize",
  "s-resize": "s-resize",
  "w-resize": "w-resize",
  "ne-resize": "ne-resize",
  "nw-resize": "nw-resize",
  "se-resize": "se-resize",
  "sw-resize": "sw-resize",
  "ew-resize": "ew-resize",
  "ns-resize": "ns-resize",
  "nesw-resize": "nesw-resize",
  "nwse-resize": "nwse-resize",
  "zoom-in": "zoom-in",
  "zoom-out": "zoom-out",
}

const maxHeight = {
  full: "100%",
  screen: "100vh",
  min: "min-content",
  max: "max-content",
  fit: "fit-content",
}

const maxWidth = {
  none: "none",
  0: "0rem",
  xs: "20rem",
  sm: "24rem",
  md: "28rem",
  lg: "32rem",
  xl: "36rem",
  "2xl": "42rem",
  "3xl": "48rem",
  "4xl": "56rem",
  "5xl": "64rem",
  "6xl": "72rem",
  "7xl": "80rem",
  full: "100%",
  min: "min-content",
  max: "max-content",
  fit: "fit-content",
  prose: "65ch",
}

const minHeight = {
  0: "0px",
  full: "100%",
  screen: "100vh",
  min: "min-content",
  max: "max-content",
  fit: "fit-content",
}

const zIndex =  {
  auto: "auto",
  0: "0",
  10: "10",
  20: "20",
  30: "30",
  40: "40",
  50: "50",
  max: "999999",
}

const colors = {
  primaryLight: "var(--color-primaryLight)",
  primary: "var(--color-primary)",
  primaryDark: "var(--color-primaryDark)",
  header: "var(--color-header)",
  topbar: "var(--color-topbar)",
  onTopbar: "var(--color-onTopbar)",
  menuButton: "var(--color-menuButton)",
  onMenuButton: "var(--color-onMenuButton)",
  infobar: "var(--color-infobar)",
  onInfobar: "var(--color-onInfobar)",
  footer: "var(--color-footer)",
  onFooter: "var(--color-onFooter)",

  onPrimary: "var(--color-onPrimary)",
  secondary: "var(--color-secondary)",
  onSecondary: "var(--color-onSecondary)",

  onSurfaceLinkHigh: "var(--color-onSurfaceLinkHigh)",
  onSurfaceLinkMedium: "var(--color-onSurfaceLinkMedium)",
  onSurfaceLinkLow: "var(--color-onSurfaceLinkLow)",

  onPrimaryLinkHigh: "var(--color-onPrimaryLinkHigh)",
  onPrimaryLinkMedium: "(--color-onPrimaryLinkMedium)",
  onPrimaryLinkLow: "var(--color-onPrimaryLinkLow)",

  onPrimaryHigh: "var(--color-onPrimaryHigh)",
  onPrimaryMedium: "var(--color-onPrimaryMedium)",
  onPrimaryLow: "var(--color-onPrimaryLow)",

  onSurfaceHigh: "var(--color-onSurfaceHigh)",
  onSurfaceMedium: "var(--color-onSurfaceMedium)",
  onSurfaceLow: "var( --color-onSurfaceLow)",

  onSurfacePrimaryHigh: "var(--color-onSurfacePrimaryHigh)",
  onSurfacePrimaryMedium: "var(--color-onSurfacePrimaryMedium)",
  onSurfacePrimaryLow: "var(--color-onSurfacePrimaryLow)",

  "surface-0": "var(--color-surface)",
  surface: "var(--color-surface)",
  "surface-1": "var(--color-surface-1)",
  "surface-2": "var(--color-surface-2)",
  "surface-3": "var(--color-surface-3)",
  "surface-4": "var(--color-surface-4)",
  "surface-5": "var(--color-surface-5)",
  "surface-6": "var(--color-surface-6)",
  "surface-7": "var(--color-surface-7)",
  "surface-8": "var(--color-surface-8)",

  background: "var(--color-background)",
  onBackgroundLow: "var(--color-onBackgroundLow)",
  onBackgroundMedium: "var(--color-onBackgroundMedium)",
  onBackgroundHigh: "var(--color-onBackgroundHigh)",

  tableHeaderBG: "var(--color-table-header-bg)",
  tableHeaderText: "var(--color-table-header-text)",
  tableHeaderBorder: "var(--color-table-header-border)",
  tableOddBG: "var(--color-table-odd-bg)",
  tableOddText: "var(--color-table-odd-text)",
  tableOddBorder: "var(--color-table-odd-border)",
  tableOddLink: "var(--color-table-even-link)",
  tableEvenBG: "var(--color-table-even-bg)",
  tableEvenText: "var(--color-table-even-text)",
  tableEvenBorder: "var(--color-table-even-border)",
  tableEvenLink: "var(--color-table-even-link)",

  red: "var(--color-red)",
  yellow: "var(--color-yellow)",
  green: "var(--color-green)",
  accentPrimary: "var(--color-accentPrimary)",
  accentSecondary: "var(--color-accentSecondary)",
  onAccentSecondary: "var(--color-onAccentSecondary)",
  accentTertiary: "var(--color-accentTertiary)",
  error: "var(--color-error)",
  success: "var(--color-success)",
  successOpacity: "var(--color-success-opacity)",
  info: "var(--color-info)",
  onError: "var(--color-onError)",
  onErrorVariant: "var(--color-onErrorVariant)",
  onSuccess: "var(--color-onSuccess)",
  onSuccessVariant: "var(--color-onSuccessVariant)",
  warning: "var(--color-warning)",
  onWarning: "var(--color-onWarning)",
  onInfo: "var(--color-onInfo)",
  onInfoVariant: "var(--color-onInfoVariant)",

  azule: "var(--color-azule)",
  azuleDark: "var(--color-azuleDark)",
  volt: "var(--color-volt)",
  voltDark: "var(--color-voltDark)",
  lobster: "var(--color-lobster)",
  lobsterDark: "var(--color-lobsterDark)",
  tulip: "var(--color-tulip)",
  sand: "var(--color-sand)",
  sandDark: "var(--color-sandDark)",
  eerie: "var(--color-eerie)",
  eerieLight: "var(--color-eerieLight)",
  darkBlue: "var(--color-darkBlue)",
  darkBlueAlt: "var(--color-darkBlueAlt)",

  black: "var(--color-black)",
  white: "var(--color-white)",
  slate: "",
  grayLight: "var(--color-grayLight)",
  gray: "var(--color-gray)",
  grayDark: "var(--color-grayDark)",
  zinc: "",
  neutral: "",
  stone:"",
  orange: "",
  amber: "",
  lime: "",
  emerald: "",
  teal: "",
  cyan: "",
  sky: "",
  blue: "",
  indigo: "",
  violet: "",
  purple: "",
  fuchsia: "",
  pink:"",
  rose: "",
  inherit: "inherit",
  current: "current",
  transparent: "transparent",
}

module.exports = {
  backgroundOpacity,
  backgroundPosition,
  borderRadius,
  borderWidth,
  colors,
  columns,
  fontSize,
  fontWeight,
  heights,
  widths,
  textOpacity,
  gridTemplateColumns,
  cursor,
  minWidth,
  maxWidth,
  maxHeight,
  minHeight,
  zIndex
};
