name: frontend

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code                    # Checksout the repository in the GitHub runner
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: Automated Version Bump                  # This action step reads and updates the version number acc to commit message
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Scaleway
        uses: docker/login-action@v2
        with:
          registry: rg.nl-ams.scw.cloud/liskscan-private-new
          username: nologin
          password: ${{ secrets.SCALEWAY_TOKEN_APP }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          push: true
          tags: rg.nl-ams.scw.cloud/liskscan-private-new/liskscan-frontend:latest,rg.nl-ams.scw.cloud/liskscan-private-new/liskscan-frontend:${{ steps.version-bump.outputs.newTag }}
      - name: Redeploy
        uses: jawher/action-scw@v2.5.4
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY_APP }}
          SCW_SECRET_KEY: ${{ secrets.SCALEWAY_TOKEN_APP }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID_APP }}
          SCW_ZONE: nl-ams-1
        with:
          args: container container update 3e8bbaa2-7b56-42d6-b6c5-97ad7c09f751 region=nl-ams redeploy=true
